import { Pathname } from "@/components/pathname";
import { validateRequest } from "@/lib/validate-request";
import type { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Stocks.tr",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { user } = await validateRequest();
  if (!user) redirect("/");
  return <Pathname>{children}</Pathname>;
}
