import { Pathname } from "@/components/pathname";
import { validateRequest } from "@/lib/validate-request";
import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { prisma } from "@/lib/prisma";

export const metadata: Metadata = {
  title: "Stocks.tr",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { user } = await validateRequest();
  if (!user) redirect("/");

  const operations =
    (await prisma.fiisOperations.findMany({
      where: { userId: user.id },
    })) ?? [];
  return <Pathname hasOperations={operations?.length > 0}>{children}</Pathname>;
}
