import { Pathname } from "@/components/pathname";
import { validateRequest } from "@/lib/validate-request";
import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { checkIfUserHasOperations } from "@/helpers/check-if-user-has-operations";

export const metadata: Metadata = {
  title: "Stocks.tr",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { user } = await validateRequest();
  if (!user) redirect("/");

  const hasOperations = await checkIfUserHasOperations(user.id);
  return <Pathname hasOperations={hasOperations}>{children}</Pathname>;
}
